project:
  type: website
  output-dir: docs

website:
  title: "Mcbeth&Sarah"

  page-footer:
    right: "&copy; MacAmma | 2026"
    center: |
          <a href="mailto:macfobi@gmail.com" class="footer-button">
            <i class="bi bi-envelope-at"></i>
          </a>
          <a href="https://github.com/mahortor" target="_blank" class="footer-button">
            <i class="bi bi-github"></i>
          </a>
    background: light
    border: false

  navbar:
    pinned: false
    logo: Idaho.jpg
    right:
      - href: index.qmd
        text: Home

      - href: "Our Story.qmd"
        text: Our Story
        
      - href: Memories.qmd
        text: Memories
        
      - href: Registry.qmd
        text: Registry

format:
  html: 
    fontsize: 1.0em
    mainfont: segoe script
    fontcolor: "white" 
    theme: 
      - cerulean
      - theme.scss
    toc: false
    code-link: true
    anchor-sections: false
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
